// Evaluate map data/popup helpers offline; no browser, network or Leaflet needed.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const code = html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
const helpers = code.slice(code.indexOf('    const norm='), code.indexOf('    function render()'));
const context = {};
vm.createContext(context);
vm.runInContext('const L={divIcon: x=>x};', context);
context.URL = URL;
vm.runInContext(helpers, context);
const pending = {pin_status:'pinned', review_status:'pending_review', latitude:35, longitude:-106};
assert.equal(context.isPinned(pending), false);
assert.equal(context.isPinned({...pending, review_status:'reviewed'}), true);
assert.equal(context.isPinned({...pending, review_status:'reviewed', duplicate_of:'another'}), false);
assert.equal(context.isPinned({...pending, review_status:'reviewed', latitude:null}), false);
assert.equal(context.isPinned({pin_status:'pinned', latitude:35, longitude:-106}), true);
assert.equal(context.sourceLink('javascript:alert(1)'), '');
const popup = context.popup({...pending, title:'<img src=x onerror=alert(1)>', summary:'A "triangle" & <script>x</script>', source_url:'https://example.com/?x="quoted"', event_date:null});
assert.equal(popup.includes('<img'), false);
assert.equal(popup.includes('<script>'), false);
assert.equal(popup.includes('Event date:'), true);
assert.equal(popup.includes('Location precision:'), true);
const reports = JSON.parse(fs.readFileSync(path.join(root,'data/uap_reports.json'), 'utf8'));
const audited = reports.filter(r=>r.audit_repair_version);
assert.equal(audited.length,73);
assert.equal(audited.filter(context.isPinned).length,0);
assert.equal(audited.filter(r=>r.duplicate_of).length,25);
console.log('Frontend checks passed: review gate, duplicate exclusion, escaped popups and 73 repaired records.');
